### ISSUE TITLE
[DA_Update_EEM] Conflicting file names found

### ISSUE THREAD

**Issue by TMaile** [BuildingSync/BuildingSync-gem#74]
We have added the BRICR measures into a branch of openstudio-ee-gem and are getting this conflicting file names issue:

The following measures exist in both gems:

- AddDaylightSensors
- create_variable_speed_rtu
- EnableDemandControlledVentilation
- EnableEconomizerControl
- ImproveFanBeltEfficiency
- ImproveMotorEfficiency
- IncreaseInsulationRValueForExteriorWalls
- IncreaseInsulationRValueForRoofs
- ReduceElectricEquipmentLoadsByPercentage
- ReduceLightingLoadsByPercentage
- ReduceSpaceInfiltrationByPercentage
- ReduceVentilationByPercentage

I created a new branch for this issue: DA_Update_EEM

```
RuntimeError: Conflicting file names found: [Measure 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/gems/openstudio-common-measures-0.2.0/lib/measures/AddDaylightSensors' conflicts with 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/bundler/gems/openstudio-ee-gem-4d595fc49b19/lib/measures/AddDaylightSensors', Measure 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/gems/openstudio-common-measures-0.2.0/lib/measures/create_variable_speed_rtu' conflicts with 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/bundler/gems/openstudio-ee-gem-4d595fc49b19/lib/measures/create_variable_speed_rtu', Measure 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/gems/openstudio-common-measures-0.2.0/lib/measures/EnableDemandControlledVentilation' conflicts with 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/bundler/gems/openstudio-ee-gem-4d595fc49b19/lib/measures/EnableDemandControlledVentilation', Measure 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/gems/openstudio-common-measures-0.2.0/lib/measures/EnableEconomizerControl' conflicts with 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/bundler/gems/openstudio-ee-gem-4d595fc49b19/lib/measures/EnableEconomizerControl', Measure 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/gems/openstudio-common-measures-0.2.0/lib/measures/ImproveFanBeltEfficiency' conflicts with 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/bundler/gems/openstudio-ee-gem-4d595fc49b19/lib/measures/ImproveFanBeltEfficiency', Measure 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/gems/openstudio-common-measures-0.2.0/lib/measures/ImproveMotorEfficiency' conflicts with 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/bundler/gems/openstudio-ee-gem-4d595fc49b19/lib/measures/ImproveMotorEfficiency', Measure 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/gems/openstudio-common-measures-0.2.0/lib/measures/IncreaseInsulationRValueForExteriorWalls' conflicts with 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/bundler/gems/openstudio-ee-gem-4d595fc49b19/lib/measures/IncreaseInsulationRValueForExteriorWalls', Measure 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/gems/openstudio-common-measures-0.2.0/lib/measures/IncreaseInsulationRValueForRoofs' conflicts with 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/bundler/gems/openstudio-ee-gem-4d595fc49b19/lib/measures/IncreaseInsulationRValueForRoofs', Measure 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/gems/openstudio-common-measures-0.2.0/lib/measures/ReduceElectricEquipmentLoadsByPercentage' conflicts with 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/bundler/gems/openstudio-ee-gem-4d595fc49b19/lib/measures/ReduceElectricEquipmentLoadsByPercentage', Measure 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/gems/openstudio-common-measures-0.2.0/lib/measures/ReduceLightingLoadsByPercentage' conflicts with 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/bundler/gems/openstudio-ee-gem-4d595fc49b19/lib/measures/ReduceLightingLoadsByPercentage', Measure 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/gems/openstudio-common-measures-0.2.0/lib/measures/ReduceSpaceInfiltrationByPercentage' conflicts with 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/bundler/gems/openstudio-ee-gem-4d595fc49b19/lib/measures/ReduceSpaceInfiltrationByPercentage', Measure 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/gems/openstudio-common-measures-0.2.0/lib/measures/ReduceVentilationByPercentage' conflicts with 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/bundler/gems/openstudio-ee-gem-4d595fc49b19/lib/measures/ReduceVentilationByPercentage']

  0) BuildingSync should parse and write building_151.xml (phase zero) with auc namespace for CAT24 and all simulations
     Failure/Error: raise "Conflicting file names found: [#{conflicts.join(', ')}]"

     RuntimeError:
       Conflicting file names found: [Measure 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/gems/openstudio-common-measures-0.2.0/lib/measures/AddDaylightSensors' conflicts with 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/bundler/gems/openstudio-ee-gem-4d595fc49b19/lib/measures/AddDaylightSensors', Measure 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/gems/openstudio-common-measures-0.2.0/lib/measures/create_variable_speed_rtu' conflicts with 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/bundler/gems/openstudio-ee-gem-4d595fc49b19/lib/measures/create_variable_speed_rtu', Measure 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/gems/openstudio-common-measures-0.2.0/lib/measures/EnableDemandControlledVentilation' conflicts with 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/bundler/gems/openstudio-ee-gem-4d595fc49b19/lib/measures/EnableDemandControlledVentilation', Measure 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/gems/openstudio-common-measures-0.2.0/lib/measures/EnableEconomizerControl' conflicts with 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/bundler/gems/openstudio-ee-gem-4d595fc49b19/lib/measures/EnableEconomizerControl', Measure 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/gems/openstudio-common-measures-0.2.0/lib/measures/ImproveFanBeltEfficiency' conflicts with 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/bundler/gems/openstudio-ee-gem-4d595fc49b19/lib/measures/ImproveFanBeltEfficiency', Measure 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/gems/openstudio-common-measures-0.2.0/lib/measures/ImproveMotorEfficiency' conflicts with 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/bundler/gems/openstudio-ee-gem-4d595fc49b19/lib/measures/ImproveMotorEfficiency', Measure 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/gems/openstudio-common-measures-0.2.0/lib/measures/IncreaseInsulationRValueForExteriorWalls' conflicts with 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/bundler/gems/openstudio-ee-gem-4d595fc49b19/lib/measures/IncreaseInsulationRValueForExteriorWalls', Measure 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/gems/openstudio-common-measures-0.2.0/lib/measures/IncreaseInsulationRValueForRoofs' conflicts with 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/bundler/gems/openstudio-ee-gem-4d595fc49b19/lib/measures/IncreaseInsulationRValueForRoofs', Measure 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/gems/openstudio-common-measures-0.2.0/lib/measures/ReduceElectricEquipmentLoadsByPercentage' conflicts with 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/bundler/gems/openstudio-ee-gem-4d595fc49b19/lib/measures/ReduceElectricEquipmentLoadsByPercentage', Measure 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/gems/openstudio-common-measures-0.2.0/lib/measures/ReduceLightingLoadsByPercentage' conflicts with 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/bundler/gems/openstudio-ee-gem-4d595fc49b19/lib/measures/ReduceLightingLoadsByPercentage', Measure 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/gems/openstudio-common-measures-0.2.0/lib/measures/ReduceSpaceInfiltrationByPercentage' conflicts with 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/bundler/gems/openstudio-ee-gem-4d595fc49b19/lib/measures/ReduceSpaceInfiltrationByPercentage', Measure 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/gems/openstudio-common-measures-0.2.0/lib/measures/ReduceVentilationByPercentage' conflicts with 'R:/NREL/BuildingSync-gem/.bundle/install/ruby/2.5.0/bundler/gems/openstudio-ee-gem-4d595fc49b19/lib/measures/ReduceVentilationByPercentage']
     # ./.bundle/install/ruby/2.5.0/gems/openstudio-extension-0.2.5/lib/openstudio/extension.rb:168:in `check_for_name_conflicts'
     # ./.bundle/install/ruby/2.5.0/gems/openstudio-extension-0.2.5/lib/openstudio/extension.rb:181:in `configure_osw'
     # ./.bundle/install/ruby/2.5.0/gems/openstudio-extension-0.2.5/lib/openstudio/extension/runner.rb:615:in`run_osw'
     # ./.bundle/install/ruby/2.5.0/gems/openstudio-extension-0.2.5/lib/openstudio/extension/runner.rb:670:in `block in run_osws'
     # ./.bundle/install/ruby/2.5.0/gems/parallel-1.19.2/lib/parallel.rb:510:in `call_with_index'
     # ./.bundle/install/ruby/2.5.0/gems/parallel-1.19.2/lib/parallel.rb:361:in `block (2 levels) in work_in_threads'
     # ./.bundle/install/ruby/2.5.0/gems/parallel-1.19.2/lib/parallel.rb:519:in `with_instrumentation'
     # ./.bundle/install/ruby/2.5.0/gems/parallel-1.19.2/lib/parallel.rb:360:in `block in work_in_threads'
     # ./.bundle/install/ruby/2.5.0/gems/parallel-1.19.2/lib/parallel.rb:211:in `block (4 levels) in in_threads'

```
